task 11.1 attempt 1
htmlacademy-javascript/2290819-kekstagram-28 pull request #10
Opened 2023-04-10 22:59 UTC by mmkattie

2023-04-10 23:07 UTC, mmkattie commented
у меня к сожалению возникли проблемы с:
1. загрузкой данных с сервера ( я не очень поняла какие именно данные надо загружать)
2. тем что окно об ошибке не показывается даже когда поля неправильно заполнены 

также я попыталась сразу включить функцию debounce как было указано в примерах, но увидела что она только в 12 разделе будет

2023-04-11 12:58 UTC, Pavel-Liteiniy requested changes

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/main.js
>  import { getSimilarMiniatures } from './data.js';
Модуль data.js больше не нужен - удаляем его и используем данные с сервера

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/main.js
>  const similarMiniatures = getSimilarMiniatures();
Это не нужно тоже соответственно

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/main.js
> +getData()
Данные запрашиваются корректно насколько я вижу и отрисовываются - можешь объяснить по подробнее в чем у тебя была проблема?

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/functions.js
> +  alertBlock.classList.add('alert-class');
Что это за класс такой 'alert-class'? Зачем он нужен?

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/functions.js
> +function debounce (callback, timeoutDelay) {
Можешь оставить если уже добавила только скажи почему function declaration?

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/validation.js
> +      getData(new FormData(evt.target))
Почему getData, тебе же нужно отправлять данные, а не получать?

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/modals.js
> +const onModalEscKeydown = (evt) => isEscapeKey(evt, closeActiveModal);
У тебя isEscapeKey умеет работать только с одним аргументом

Вот как эта функция выглядит сейчас
`const isEscapeKey = (evt) => evt.key === 'Escape';`

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/validation.js
> +const onImageLoadEscKeyDown = (evt) => onEscKeyDown(evt, closeImgUpload);
У тебя  же onEscKeyDown умеет работать только с одним аргументом почему ты вызываешь функцию с двумя?

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/validation.js
> +      getData(new FormData(evt.target))
Ты пытаешься отправить запрос на сервер внутри условия - кажется это нелогично)
if (!pristine.validate()) { // если форма не прошла валидацию то код здесь выполнится //}


По идее логика коллбека должны быть такая
- отменяем дефолтное поведение при сабмите формы preventDefault
- если форма валидна, то
  - блокируем кнопку "опубликовать"
  - отправляем запрос на сервер
      - если запрос успешно отправился то закрываем форму сбрасывая данные в ней и показываем попап с информацией, что все прошло успешно
      - если запрос упал, то закрываем форму **не** сбрасывая данные и показываем попап с информацией, что все плохо
  - разблокируем кнопку опубликовать

2023-04-11 12:58 UTC, Pavel-Liteiniy commented on js/validation.js
> +          showSuccessModal();
Кажется сейчас success modal и error modal не получается закрыть при нажатии на клавишу ESC - поправь, пожалуйста)

2023-04-12 09:39 UTC, Pavel-Liteiniy requested changes

2023-04-12 09:39 UTC, Pavel-Liteiniy commented on js/modals.js
> +  isEscapeKey(evt);
Как это должно работать?)

Эта функция возвращает булевое значение
`const isEscapeKey = (evt) => evt.key === 'Escape';`

если тебе нужно вызвать `closeActiveModal` только при нажатии на клавишу esc, то оберни ее в `if`

сейчас у тебя `isEscapeKey` отрабатывает в пустоту)

2023-04-12 09:39 UTC, Pavel-Liteiniy commented on js/validation.js
> +    button.disabled = false;
Сейчас кнопка "разблокируется" не дожидаясь окончания запроса `sendData`

Положи `button.disabled = false;` внутрь `.finally();`

2023-04-12 09:39 UTC, Pavel-Liteiniy commented on js/validation.js
> +    } else {
Блок else не нужен - если форма не прошла валидацию, то пользователь будет видеть твои сообщения об ошибках под инпутами 
- 'Хэштеги указаны неверно';
- 'Вы превысили максимальную длину комментария';

2023-04-12 09:39 UTC, Pavel-Liteiniy commented on js/validation.js
> +          document.addEventListener('keydown', closeMessage());
Почему ты вызываешь функцию `closeMessage`? Не очень понимаю как это должно работать

2023-04-12 09:55 UTC, Pavel-Liteiniy commented on js/validation.js
> +      getData(new FormData(evt.target))
Этот [пункт ТЗ](https://up.htmlacademy.ru/javascript/28/project/kekstagram#kekstagram-3-5) не выполняем

> В таком случае вся введённая пользователем информация сохраняется, чтобы у него была возможность отправить форму повторно.

2023-04-12 11:43 UTC, merged