homework 8 draft
htmlacademy-javascript/2290819-kekstagram-28 pull request #6
Opened 2023-03-29 20:43 UTC by mmkattie

2023-03-30 04:27 UTC, Pavel-Liteiniy requested changes

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +const isEscapeKey = (evt) => evt.key === 'Escape';
давай эту функцию вынесем в отдельный модуль - functions.js отлично подойдет

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +const bigLikes = document.querySelector('.likes-count');
```suggestion
const bigLikes = bigPicture.querySelector('.likes-count');
```

И ниже проверь где можно оптимизировать/сузить поиск элементов

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +  body.classList.add('.modal-open');
```suggestion
  body.classList.add('modal-open');
```

Если работаешь с `classList` то достаточно просто названия класса. Проверь в других местах тоже)

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +const addPictureClickHandler = function (picture) {
Давай при вызове `addPictureClickHandler` будем передавать в него еще один аргумент - объект миниатюры со всеми данными. Так мы сможем брать информацию из этого объекта.

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +  commentCount.classList.add('.hidden');
Давай пока что вынесем эти две строчки из функции наверх, чтобы код выполнялся только один раз - при загрузке модуля

```
commentCount.classList.add('.hidden');
commentLoader.classList.add('hidden');
```

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +
Давай попробуем разделить код на более маленькие функции.

Можешь декомпозировать например на такие функции:
- Отображение bigPicture
- Скрытие bigPicture
- Создание одного комментария
- Отрисовка всех комментариев
- Добавление данный в bigPicture
- Удаление данных в bigPicture
- ...

После этого собери функцию addPictureClickHandler из этих мини-функций

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +for (let i = 0; i < pictures.length; i++) {
Этот цикл нужно убрать - вместо него давай будем экспортировать функцию  `addPictureClickHandler` из модуля и вызывать ее внутри `renderMiniatures`

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/ popup.js
> +document.addEventListener('keydown', (evt) => {
Так мы добавляем обработчик события один раз при загрузке модуля - по ТЗ нам нужно, чтобы обработчик добавлялся при открытии bigPicture и удалялся при закрытии bigPicture.

- объяви саму функцию коллбэк
- добавляй обработчик события с этим коллбэком внутри функции которая показывает bigPicture
- удаляй обработчик события с этим коллбэком внутри функции которая скрывает bigPicture

2023-03-30 04:27 UTC, Pavel-Liteiniy commented on js/main.js
> +const bigPicture = document.querySelector('.big-picture');
здесь код дублируется - удали его пожалуйста)

2023-03-30 04:29 UTC, Pavel-Liteiniy requested changes

2023-03-30 04:29 UTC, Pavel-Liteiniy commented on js/data.js
> +  comments: Array.from({length: getRandomPositiveInteger(COMMENT_MINIMAL_COUNT, COMMENT_MAXIMAL_COUNT)},(_, commentIndex) => createComment(commentIndex + 1))
Зачем передаешь аргумент в createComment, разве он будет использоваться?))

```
const createComment = () => ({
  id: generateRandomCommentId(),
  avatar: `img/avatar-${getRandomPositiveInteger(AVATAR_MINIMAL_COUNT,AVATAR_MAXIMAL_COUNT)}.svg`,
  message: getRandomArrayElement(MESSAGES),
  name: getRandomArrayElement(NAMES)
});
```

2023-03-30 22:24 UTC, mmkattie commented on js/ popup.js
> +
Я постаралась разбить код на маленькие функции, с помощью создания bigPictureClose etc., но, возможно, не до конца поняла, как это сделать.

2023-03-30 22:24 UTC, mmkattie commented on js/ popup.js
> +for (let i = 0; i < pictures.length; i++) {
Я попробовала так сделать, но у меня все сломалось. И, если честно, я не очень поняла как я могу вызывать appClickHandler внутри renderMiniatures, если мне нужно еще передать аргументы с индексом i. То есть для этого мне придется еще экспортировать const pictures? и вызывать appClickHandler надо будет в объявлении renderMiniatures в файле miniatures.js?

2023-03-30 22:24 UTC, mmkattie commented on js/main.js
> +const bigPicture = document.querySelector('.big-picture');
Я туплю, наверное, но  я не понимаю, какая строчка дублируется(

2023-04-02 07:37 UTC, Pavel-Liteiniy requested changes

2023-04-02 07:37 UTC, Pavel-Liteiniy commented on js/functions.js
> +export {addElement};
Если решили делать экспорт в конце файла, то давай объявлять его один раз

```suggestion
export {
    isEscapeKey,
    addElement,
};
```

2023-04-02 07:37 UTC, Pavel-Liteiniy commented on js/ popup.js
> +import { isEscapeKey } from './functions.js';
В проекте два файла - один нужно убрать)

`js/ popup.js` и `js/popup.js`

2023-04-03 03:24 UTC, merged